[package]
name = "boilerrate"
version = "0.1.0"
edition = "2024"

[dependencies]
axum = "0.8.4"
hmac = "0.12.1"
jwt = "0.16.0"
serde = { version = "1.0.219", features = ["derive"] }
sha2 = "0.10.9"
tokio = { version = "1.47.1", features = ["full"] }
